/*
 * jos_delay.h
 *
 *  Created on: Jan 14, 2025
 *      Author: andy
 */

#pragma once

// Coefficient table and structure are generated by Python

template<int S> struct JosDelayData {
  int tab_len;
  int oversamp_bits;
  bool allow_overflow;
  float coef_set[S];

};
