# Project Name
TARGET = SimpleOscillator

# Sources
CPP_SOURCES = TryStreaming.cpp

# Library Locations
DAISY_BASE = /Users/andy/Dropbox/Developer/AudioDev/DaisyExamples
LIBDAISY_DIR = $(DAISY_BASE)/libDaisy
DAISYSP_DIR = $(DAISY_BASE)/DaisySP

OPT = -O0

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

