from __future__ import annotations
__all__ = ['Abs', 'Add', 'Comparator', 'EdgeDetector', 'EdgeDetectorParams', 'EdgeDetectorState', 'Exp', 'Log', 'Mult', 'Sqrt', 'Square', 'Sub']
class Abs:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def proc(self, buffers: list) -> None:
        ...
class Add:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def proc(self, buffers: list) -> None:
        ...
class Comparator:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def proc(self, bufs: list) -> None:
        ...
class EdgeDetector:
    params: EdgeDetectorParams
    state: EdgeDetectorState
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def proc(self, bufs: list) -> None:
        ...
class EdgeDetectorParams:
    mode: int
    thresh: float
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
class EdgeDetectorState:
    prev_samp: float
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
class Exp:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def proc(self, buffers: list) -> None:
        ...
class Log:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def proc(self, buffers: list) -> None:
        ...
class Mult:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def proc(self, buffers: list) -> None:
        ...
class Sqrt:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def proc(self, buffers: list) -> None:
        ...
class Square:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def proc(self, buffers: list) -> None:
        ...
class Sub:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def proc(self, buffers: list) -> None:
        ...
